# PROD environment — smoke only
base.url=https://restful-booker.herokuapp.com
auth.endpoint=/auth
auth.username=admin
auth.password=password123
auth.type=COOKIE_TOKEN
basic.auth.header=${RB_PROD_BASIC_AUTH}
