# PROD environment — smoke only
base.url=https://restful-booker.herokuapp.com
auth.endpoint=/auth
auth.username=${RB_PROD_USERNAME}
auth.password=${RB_PROD_PASSWORD}
auth.type=COOKIE_TOKEN
basic.auth.header=${RB_PROD_BASIC_AUTH}
